### ISSUE TITLE
Framework should be marked dynamic in Package.swift

### ISSUE THREAD

**Issue by bratxdy** [urbanairship/apptimize-ios-kit#2]
When building to device after integrating the Apptimize via SPM we are seeing the error: `Library not loaded: @rpath/Apptimize.framework/Apptimize`

It seems that library needs to be marked as dynamic in the Package.swift so that we can choose to embed it in our app properly. 

I found this workout https://appmetrica.yandex.com/docs/troubleshooting/trouble-with-spm.html#library-not-found that works, but should not be a permanent solution.

**Comment by bratxdy** [comment]
Some more context here. Our project contains multiple local dynamic frameworks. In this case Apptimize was added to our Experimentation framework (for obfuscation purposes) so that we can share it across our various apps. It looks like this is the core of the problem. Integrating Appetimize directly into our main app works fine. I believe if the Swift Package is marked as dynamic that will give us the freedom to embed the framework in the correct place.

**Comment by pattessm** [comment]
Would love to see this fixed, as I have the same problem. It would be nice to share our experimentation libraries across applications.

**Comment by nickoto** [comment]
I believe that you are experiencing this bug: [SR-13343 - SwiftPM fails to codesign with binaryTarget and embedded frameworks](https://bugs.swift.org/browse/SR-13343).

Unfortunately we cannot make a change to the library type. As we distribute the library as a binary framework swift package manager requires that the library type be left as automatic. You will have to continue using your workaround until Apple fixes the issue.

Please see the swift package manager source [ManifestLoader.swift](https://github.com/apple/swift-package-manager/blob/bf7ee58708e036a07ddc81599000968ddf4a5657/Sources/PackageLoading/ManifestLoader.swift#L345-L349
) package validation which requires that the binary framework target type be left as automatic.
