### ISSUE TITLE
Apptimize version 3.5.13 has an issue with the binary target

### ISSUE THREAD

**Issue by CorbinMontague** [urbanairship/apptimize-ios-kit#3]
SPM is unable to resolve the Apptimize version 3.5.13 with error:
`checksum of downloaded artifact of binary target 'Apptimize' (15b60934e93d3fc22a931d6527404a80cba1b4bd02d585e101ff401daa050643) does not match checksum specified by the manifest (845e49b5c0f991aa5cd4a1281b949abc0982d54b65ba8995ac622004cb2b9eae)`

**Comment by bratxdy** [comment]
We are also seeing this issue with the latest version.

**Comment by ilitvinenko** [comment]
Thanks for reporting the issue. We have updated all checksums. Please try to resolve the 3.5.13. You might want to do Reset local cache to get the latest version.
